name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run build bazel
      run: make build_bazel

    - name: Run build bazel.gpu
      run: make build_bazel_gpu
    
    - name: docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    
    - name: docker push-logout
      run: |
        docker push tradingai/bazel:latest
        docker push tradingai/bazel:gpu-latest
        docker logout

    - name: ali docker login
      run:  echo "${{ secrets.ALI_DOCKER_PASSWORD }}" | docker login -u ${{ secrets.ALI_DOCKER_USERNAME }} registry.cn-hangzhou.aliyuncs.com --password-stdin

    - name: ali docker push-logout
      run: |
        docker tag tradingai/bazel:latest registry.cn-hangzhou.aliyuncs.com/tradingai/bazel:latest
        docker tag tradingai/bazel:gpu-latest registry.cn-hangzhou.aliyuncs.com/tradingai/bazel:gpu-latest
        docker push registry.cn-hangzhou.aliyuncs.com/tradingai/bazel:latest
        docker push registry.cn-hangzhou.aliyuncs.com/tradingai/bazel:gpu-latest
        docker logout
